openapi: 3.0.0
info:
  title: Recipes CRUD API
  version: 1.0.0
servers:
  - url: http://localhost:4201
paths:
  /recipes:
    get:
      summary: Get all recipes
      responses:
        200:
          description: All recipes returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
  /recipes/{id}:
    get:
      summary: Get a single recipe by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Recipe returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        404:
          description: Recipe not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Recipe not found
  /recipes/add:
    post:
      summary: Add a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        200:
          description: Recipe added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: 6074fb9d8eadce169efafdfb
  /recipes/edit/{id}:
    put:
      summary: Edit a recipe by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        200:
          description: Recipe edited
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: Recipe edited
        404:
          description: Recipe not found or not modified
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Recipe not found or not modified
  /recipes/delete/{id}:
    delete:
      summary: Delete a recipe by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Recipe deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: Recipe deleted
        404:
          description: Recipe not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Recipe not found
components:
  schemas:
    Recipe:
      type: object
      properties:
        _id:
          type: string
          example: 6074fb9d8eadce169efafdfb
        name:
          type: string
          example: Chocolate Cake
        ingredients:
          type: array
          items:
            type: string
            example:
            - 2 cups all-purpose flour
            - 2 cups granulated sugar
            - 3/4 cup unsweetened cocoa powder
            - 1 1/2 tsp baking powder
            - 1 1/2 tsp baking soda
            - 1 tsp salt
            - 2 large eggs
            - 1 cup whole milk
            - 1/2 cup vegetable oil
            - 2 tsp vanilla extract
            - 1 cup boiling water
        instructions:
          type: array
          items:
            type: string
            example:
              - Preheat oven to 350°F (175°C). Grease and flour two 9-inch cake pans.
              - In a large bowl, whisk together flour, sugar, cocoa, baking powder, baking soda, and salt.
              - Add eggs, milk, oil, and vanilla extract. Mix until well combined.
              - Stir in boiling water until fully incorporated. The batter will be thin.
              - Divide the batter evenly between the prepared cake pans.
              - Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.
              - Remove cakes from the oven and let cool in the pans for 10 minutes. Then, transfer cakes to a wire rack to cool completely.
              - Once the cakes have cooled, frost with your favorite chocolate frosting or ganache.    
        image: 
          type: string
          example: http://via.placeholder.com/640x360
        tags: 
          type: string
          example: breakfast, vegan
        rating: 
          type: number
          example: 4.2
        notes: 
          type: string
          example: best served immediately
        source: 
          type: string
          example: http://www.seriouseats.com/recipes/2011/02/chocolate-cake-recipe.html
        date: 
          type: string
          example: 2021-04-14T00:00:00.000Z
        id: 
          type: number
          example: 12
      required:
        - name
        - ingredients
        - instructions
        - id
